import 'package:plugin_platform_interface/plugin_platform_interface.dart';
import 'c_shield_sdk_method_channel.dart';

abstract class CShieldSdkPlatform extends PlatformInterface {
  CShieldSdkPlatform() : super(token: _token);

  static final Object _token = Object();
  static CShieldSdkPlatform _instance = MethodChannelCShieldSdk();

  static CShieldSdkPlatform get instance => _instance;

  static set instance(CShieldSdkPlatform v) {
    PlatformInterface.verifyToken(v, _token);
    _instance = v;
  }

  // ── SDK ──────────────────────────────────────────────────────────────────
  Future<void> initialize() => throw UnimplementedError();

  // Stream<LoadAppThreatEvent> threatEvents() => throw UnimplementedError();

  // ── RASP ─────────────────────────────────────────────────────────────────
  Future<String> raspBuild({required Map<String, bool> flags}) =>
      throw UnimplementedError();

  Future<void> raspSetConfig({
    required String checkerId,
    required Map<String, dynamic> config,
  }) => throw UnimplementedError();

  Future<String> raspQuickCheck({required String checkerId}) =>
      throw UnimplementedError();

  // [subscriptionId] is generated by Dart and passed down so the event bus
  // can start listening before native fires any events.
  Future<void> raspSubscribe({
    required String checkerId,
    required String subscriptionId,
    required bool detail,
    required bool automaticallyShowPopup,
  }) => throw UnimplementedError();

  Future<void> raspCancelSubscribe({required String subscriptionId}) =>
      throw UnimplementedError();

  Future<void> raspDispose({required String checkerId}) =>
      throw UnimplementedError();

  // ── SSL ──────────────────────────────────────────────────────────────────
  Future<void> sslConfigure({
    required List<String> pins,
    required String hostname,
  }) => throw UnimplementedError();

  Future<void> sslUpdatePins({
    required List<String> pins,
    required String hostname,
  }) => throw UnimplementedError();

  Future<bool> sslIsConfigured() => throw UnimplementedError();

  Future<bool> sslCheckServerTrusted({
    required String certDerBase64,
    required String host,
  }) => throw UnimplementedError();

  // ── AIP ──────────────────────────────────────────────────────────────────
  // Only the cryptographic sign/verify cross to native (they need the device
  // key and proxy-CA check). Body normalization, payload construction, hashing
  // and the timestamp-window check all happen in Dart (see AIPNormalizer /
  // CShieldAIP) — no fabricated request URL required.
  Future<String> aipSign({required String payload}) => throw UnimplementedError();

  Future<void> aipVerify({
    required String payload,
    required String signature,
  }) => throw UnimplementedError();

}
